### ISSUE TITLE
Jpeople doesn't work with sane cookie settings

### ISSUE THREAD

**Issue by grunweg** [OpenJUB/jPeople#3]
When trying to use jpeople (https://jpeople.jacobs-cs.club/) first, I never worked for me. Now I found out why, and that smells a lot like a bug in this code.

STR:
(0. Be on the Jacobs campus, connected via the Jacobs networks.)
1. Open the browser preferences window. In the "Privacy" tab, make sure to have "accept cookies from sites" checked; under "keep cookies until" choose the option "ask me first". Make sure to clear any cookies from "jacobs-cs.club" you might have.
1. Go to jpeople (with the url above), type e.g. "Test" into the search bar. 
2. Now leave the page, clear browser cache and all cookies; and set "keep cookies until" to "they expire". 
3. Visit jpeople and query for "Test" again.
Happens with Iceweasel (a.k.a. Mozilla Firefox) 31.3.0. on Debian stable, also in safe mode.

Actual results:
In step 1, I get an "Error: Please log in or connect to VPN to be virtually on campus" message all the time. This also happens when I log in with my Jacobs credentials before searching. Looking at my browser's cookie list, I see that no cookies get set from the site, regardless of what I do. In step 3, however, everything "just works" (i.e. i get sane results out of jPeople), regardless of whether I'm logged in. I see cookies from the domain "jacobs-cs.club" being set.

Expected results:
Toggling this one preference should not make a difference. I should get asked for whether I want to accept cookies from that site - but that's it. 
I do not want all web pages to track me - therefore I need to have a sane setting for my cookies. This bug hence requires either repeated fiddling with my preferences (user unfriendly) or running my browser with bad privacy settings. Neither is good.

**Comment by grunweg** [comment]
Re-testing now, everything works fine. Thanks for your work!

**Comment by tkw1536** [comment]
@grunweg Jup, that's cause I re-wrote it a while ago. Although images a re broken when logging in off-campus right now.
