### ISSUE TITLE
Multiple entries with same name, but different data

### ISSUE THREAD

**Issue by grunweg** [OpenJUB/jPeople#5]
There are some duplicate entries in the database now. For example, visit the official site https://jpeople.jacobs-cs.club/ and search for "Steffen Maaß" - you'll see two entries, one with email, room and phone number and one without all that stuff. I also found a duplicate entry for "Svenja Schönbrunn".
Maybe this is expected as admin just added the data for him and the synchronisation is not working yet - but in any case, this would be good to have fixed.

**Comment by tkw1536** [comment]
I am in progress of writing a new version. This issue had been fixed in
there. However it is still unstable and I will not have to much time to fix
outstanding issues until the weekend.

**Comment by grunweg** [comment]
Any way for mere mortals to access the in-progress version already?

**Comment by tkw1536** [comment]
No not really, sorry. This is actually in the backend (openjub-api). I
would have to deploy a second backend with a separate db instance and let
the jpeople client access that. Too much trouble for now.

**Comment by tkw1536** [comment]
I did have some time and the new version has been deployed.
