### ISSUE TITLE
Jpeople doesn't work off campus

### ISSUE THREAD

**Issue by grunweg** [OpenJUB/jPeople#7]
Tested on a current Debian GNU/Linux (v8.2, codenamed Jessie) with Iceweasel 38.2.1, also in a fresh profile.
1. Go to https://jpeople.jacobs-cs.club/.
2. Click on the 'Log in' button (as I'm off campus at the moment)..
3. The OpenJUB window pops up, I enter my credentials and click on Log in via OpenJUB.
4. The window closes, and no change is visible to the jpeople page (even after force-reloading). No cookies are present. And obviously entering any search terms doesn't bring up any results.

If there are other tests I can perform to narrow down the problem, I'll be happy to help.

**Comment by tkw1536** [comment]
The problem seems to be with firefox, it works fine in Chrome.

**Comment by tkw1536** [comment]
Problem has been fixed. I have tested it with firefox on archlinux (You might have to clear your browser cache for it to work. )
